apiVersion: v2
name: ai-ml-observability
description: AI/ML Observability Reference Architecture
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: 76.3.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-stack.enabled
  - name: opensearch-operator
    version: 2.7.0
    repository: https://opensearch-project.github.io/opensearch-k8s-operator/
    condition: opensearch.enabled
  - name: fluent-operator
    version: 3.2.0
    repository: https://fluent.github.io/helm-charts
    condition: fluentbit.enabled
  - name: opencost
    version: 1.43.2
    repository: https://opencost.github.io/opencost-helm-chart
    condition: opencost.enabled