{{- if .Values.endpoints.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-workers-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  jobLabel: ray-workers
  selector:
    matchLabels:
      ray.io/node-type: worker
  podMetricsEndpoints:
    - port: metrics
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_ray_io_cluster
          targetLabel: ray_io_cluster
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_host_ip
          targetLabel: node_instance
{{- end }}
