{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.opensearch.credentials.adminUsername | b64enc | quote }}
  password: {{ .Values.opensearch.credentials.adminPassword | b64enc | quote }}
{{- end }}