---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-mcp-server
  namespace: monitoring
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-mcp-server
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: kubernetes-mcp-server
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetes-mcp-server
  namespace: monitoring
  labels:
    app: kubernetes-mcp-server
spec:
  selector:
    matchLabels:
      app: kubernetes-mcp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-mcp-server
        deployment: kubernetes-mcp-server
    spec:
      serviceAccountName: kubernetes-mcp-server
      containers:
        - name: server
          image: quay.io/containers/kubernetes_mcp_server:v0.0.57
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-mcp-server
  namespace: monitoring
  labels:
    app: kubernetes-mcp-server
spec:
  selector:
    app: kubernetes-mcp-server
    deployment: kubernetes-mcp-server
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
